# Generated by Django 6.0.2 on 2026-02-15 08:53
# Fixed: всё обёрнуто в SeparateDatabaseAndState — таблицы создаются
# реальными приложениями (partners, personnel, contracts, ...), а здесь
# мы только регистрируем состояние, чтобы миграция 0002 могла их удалить.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('personnel', '0001_initial'),
        ('catalog', '0001_initial'),
        ('contracts', '0001_initial'),
        ('deliveries', '0001_initial'),
        ('warehousing', '0001_initial'),
    ]

    operations = [
        # Все CreateModel — только state-операции (таблицы уже есть в других приложениях)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Accountant",
                    fields=[
                        ("id_accountant", models.AutoField(primary_key=True, serialize=False, verbose_name="ID бухгалтера")),
                        ("full_name", models.CharField(max_length=200, verbose_name="Полное имя")),
                        ("contact_information", models.CharField(max_length=300, verbose_name="Контактная информация")),
                    ],
                    options={"verbose_name": "Бухгалтер", "verbose_name_plural": "Бухгалтеры", "db_table": "accountant"},
                ),
                migrations.CreateModel(
                    name="ActOfArrival",
                    fields=[
                        ("id_act_of_arrival", models.AutoField(primary_key=True, serialize=False, verbose_name="ID акта прибытия")),
                        ("status", models.CharField(choices=[("Delivered", "Доставлено"), ("Not Delivered", "Не доставлено"), ("Cancel", "Отменено")], max_length=20, verbose_name="Статус")),
                    ],
                    options={"verbose_name": "Акт прибытия", "verbose_name_plural": "Акты прибытия", "db_table": "act_of_arrival"},
                ),
                migrations.CreateModel(
                    name="Contract",
                    fields=[
                        ("id_contract", models.AutoField(primary_key=True, serialize=False, verbose_name="ID договора")),
                    ],
                    options={"verbose_name": "Договор", "verbose_name_plural": "Договоры", "db_table": "contract"},
                ),
                migrations.CreateModel(
                    name="Director",
                    fields=[
                        ("id_director", models.AutoField(primary_key=True, serialize=False, verbose_name="ID директора")),
                        ("full_name", models.CharField(max_length=200, verbose_name="Полное имя")),
                        ("contact_information", models.CharField(max_length=300, verbose_name="Контактная информация")),
                    ],
                    options={"verbose_name": "Директор", "verbose_name_plural": "Директора", "db_table": "director"},
                ),
                migrations.CreateModel(
                    name="Manager",
                    fields=[
                        ("id_manager", models.AutoField(primary_key=True, serialize=False, verbose_name="ID менеджера")),
                        ("full_name", models.CharField(max_length=200, verbose_name="Полное имя")),
                        ("contact_information", models.CharField(max_length=300, verbose_name="Контактная информация")),
                    ],
                    options={"verbose_name": "Менеджер", "verbose_name_plural": "Менеджеры", "db_table": "manager"},
                ),
                migrations.CreateModel(
                    name="Materials",
                    fields=[
                        ("id_materials", models.AutoField(primary_key=True, serialize=False, verbose_name="ID материала")),
                        ("name", models.CharField(max_length=300, verbose_name="Название материала")),
                        ("unit_of_measurement", models.CharField(max_length=30, verbose_name="Единица измерения")),
                        ("description", models.CharField(max_length=500, verbose_name="Описание")),
                    ],
                    options={"verbose_name": "Материал", "verbose_name_plural": "Материалы", "db_table": "materials"},
                ),
                migrations.CreateModel(
                    name="Storekeeper",
                    fields=[
                        ("id_storekeeper", models.AutoField(primary_key=True, serialize=False, verbose_name="ID кладовщика")),
                        ("full_name", models.CharField(max_length=180, verbose_name="Полное имя")),
                        ("contact_information", models.CharField(max_length=300, verbose_name="Контактная информация")),
                    ],
                    options={"verbose_name": "Кладовщик", "verbose_name_plural": "Кладовщики", "db_table": "storekeeper"},
                ),
                migrations.CreateModel(
                    name="Supplier",
                    fields=[
                        ("id_supplier", models.AutoField(primary_key=True, serialize=False, verbose_name="ID поставщика")),
                        ("name", models.CharField(max_length=200, verbose_name="Название компании")),
                        ("tax_id", models.CharField(max_length=200, verbose_name="ИНН/Налоговый номер")),
                        ("accounted_full_name", models.CharField(max_length=200, verbose_name="ФИО бухгалтера")),
                        ("director_full_name", models.CharField(max_length=200, verbose_name="ФИО директора")),
                        ("payment_details", models.CharField(max_length=500, verbose_name="Платежные реквизиты")),
                    ],
                    options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики", "db_table": "supplier"},
                ),
                migrations.CreateModel(
                    name="Warehouse",
                    fields=[
                        ("id_warehouse", models.AutoField(primary_key=True, serialize=False, verbose_name="ID склада")),
                        ("name", models.CharField(max_length=200, verbose_name="Название склада")),
                        ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                    ],
                    options={"verbose_name": "Склад", "verbose_name_plural": "Склады", "db_table": "warehouse"},
                ),
                migrations.CreateModel(
                    name="Delivery",
                    fields=[
                        ("id_delivery", models.AutoField(primary_key=True, serialize=False, verbose_name="ID поставки")),
                        ("status", models.CharField(choices=[("Delivered", "Доставлено"), ("Not Delivered", "Не доставлено"), ("Cancel", "Отменено")], max_length=20, verbose_name="Статус")),
                        ("delivery_date", models.DateField(verbose_name="Дата поставки")),
                        ("id_act_of_arrival", models.ForeignKey(db_column="id_act_of_arrival", on_delete=django.db.models.deletion.CASCADE, to="users.actofarrival", verbose_name="Акт прибытия")),
                        ("id_contract", models.ForeignKey(db_column="id_contract", on_delete=django.db.models.deletion.CASCADE, to="users.contract", verbose_name="Договор")),
                    ],
                    options={"verbose_name": "Поставка", "verbose_name_plural": "Поставки", "db_table": "delivery"},
                ),
                migrations.CreateModel(
                    name="Prices",
                    fields=[
                        ("id_prices", models.AutoField(primary_key=True, serialize=False, verbose_name="ID цены")),
                        ("effective_dates", models.DateField(verbose_name="Дата начала действия")),
                        ("price", models.FloatField(verbose_name="Цена")),
                        ("id_materials", models.ForeignKey(db_column="id_materials", on_delete=django.db.models.deletion.CASCADE, to="users.materials", verbose_name="Материал")),
                        ("id_supplier", models.ForeignKey(db_column="id_supplier", on_delete=django.db.models.deletion.CASCADE, to="users.supplier", verbose_name="Поставщик")),
                    ],
                    options={"verbose_name": "Цена", "verbose_name_plural": "Цены", "db_table": "prices"},
                ),
                migrations.CreateModel(
                    name="Concluded",
                    fields=[
                        ("conclusion_dates", models.DateField(verbose_name="Дата заключения")),
                        ("payment_date", models.DateField(verbose_name="Дата оплаты")),
                        ("cost", models.FloatField(verbose_name="Стоимость")),
                        ("id_contract", models.OneToOneField(db_column="id_contract", on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="users.contract", verbose_name="Договор")),
                        ("id_accountant", models.ForeignKey(db_column="id_accountant", on_delete=django.db.models.deletion.CASCADE, to="users.accountant", verbose_name="Бухгалтер")),
                        ("id_director", models.ForeignKey(db_column="id_director", on_delete=django.db.models.deletion.CASCADE, to="users.director", verbose_name="Директор")),
                        ("id_manager", models.ForeignKey(db_column="id_manager", on_delete=django.db.models.deletion.CASCADE, to="users.manager", verbose_name="Менеджер")),
                        ("id_supplier", models.ForeignKey(db_column="id_supplier", on_delete=django.db.models.deletion.CASCADE, to="users.supplier", verbose_name="Поставщик")),
                    ],
                    options={"verbose_name": "Заключенный договор", "verbose_name_plural": "Заключенные договоры", "db_table": "concluded"},
                ),
                migrations.CreateModel(
                    name="MaterialsInContract",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("materials_quality_in_contract", models.FloatField(verbose_name="Качество материалов в договоре")),
                        ("condition", models.CharField(max_length=200, verbose_name="Состояние/условие")),
                        ("actual_quantity", models.FloatField(verbose_name="Фактическое количество")),
                        ("id_contract", models.ForeignKey(db_column="id_contract", on_delete=django.db.models.deletion.CASCADE, to="users.contract", verbose_name="Договор")),
                        ("id_materials", models.ForeignKey(db_column="id_materials", on_delete=django.db.models.deletion.CASCADE, to="users.materials", verbose_name="Материал")),
                    ],
                    options={"verbose_name": "Материал в договоре", "verbose_name_plural": "Материалы в договоре", "db_table": "materials_in_contract", "unique_together": {("id_materials", "id_contract")}},
                ),
                migrations.CreateModel(
                    name="AcceptanceOfDelivery",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("id_act_of_arrival", models.ForeignKey(db_column="id_act_of_arrival", on_delete=django.db.models.deletion.CASCADE, to="users.actofarrival", verbose_name="Акт прибытия")),
                        ("id_storekeeper", models.ForeignKey(db_column="id_storekeeper", on_delete=django.db.models.deletion.CASCADE, to="users.storekeeper", verbose_name="Кладовщик")),
                    ],
                    options={"verbose_name": "Приемка поставки", "verbose_name_plural": "Приемки поставок", "db_table": "acceptance_of_delivery", "unique_together": {("id_storekeeper", "id_act_of_arrival")}},
                ),
                migrations.CreateModel(
                    name="Inventory",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("quantity", models.FloatField(verbose_name="Количество")),
                        ("id_materials", models.ForeignKey(db_column="id_materials", on_delete=django.db.models.deletion.CASCADE, to="users.materials", verbose_name="Материал")),
                        ("id_warehouse", models.ForeignKey(db_column="id_warehouse", on_delete=django.db.models.deletion.CASCADE, to="users.warehouse", verbose_name="Склад")),
                    ],
                    options={"verbose_name": "Запас", "verbose_name_plural": "Запасы", "db_table": "inventory", "unique_together": {("id_warehouse", "id_materials")}},
                ),
                migrations.CreateModel(
                    name="Works",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("id_storekeeper", models.ForeignKey(db_column="id_storekeeper", on_delete=django.db.models.deletion.CASCADE, to="users.storekeeper", verbose_name="Кладовщик")),
                        ("id_warehouse", models.ForeignKey(db_column="id_warehouse", on_delete=django.db.models.deletion.CASCADE, to="users.warehouse", verbose_name="Склад")),
                    ],
                    options={"verbose_name": "Работает", "verbose_name_plural": "Работают", "db_table": "works", "unique_together": {("id_storekeeper", "id_warehouse")}},
                ),
            ],
        ),
    ]
