# Generated by Django 6.0.2 on 2026-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id_accountant', models.AutoField(primary_key=True, serialize=False, verbose_name='ID бухгалтера')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('contact_information', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Бухгалтер',
                'verbose_name_plural': 'Бухгалтеры',
                'db_table': 'accountant',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False, verbose_name='ID директора')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('contact_information', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директора',
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id_manager', models.AutoField(primary_key=True, serialize=False, verbose_name='ID менеджера')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('contact_information', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Storekeeper',
            fields=[
                ('id_storekeeper', models.AutoField(primary_key=True, serialize=False, verbose_name='ID кладовщика')),
                ('full_name', models.CharField(max_length=180, verbose_name='Полное имя')),
                ('contact_information', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Кладовщик',
                'verbose_name_plural': 'Кладовщики',
                'db_table': 'storekeeper',
            },
        ),
    ]
