# Generated by Django 6.0.2 on 2026-03-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0005_concluded_delivery_date_concluded_is_paid_and_more'),
        ('partners', '0002_add_status_to_supplier'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процентная ставка')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('due_date', models.DateField(verbose_name='Дата погашения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paid', 'Погашен'), ('overdue', 'Просрочен')], default='active', max_length=20, verbose_name='Статус')),
                ('creditor_name', models.CharField(max_length=300, verbose_name='Кредитор')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('due_date', models.DateField(verbose_name='Дата погашения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачена'), ('overdue', 'Просрочена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id_concluded', models.ForeignKey(blank=True, db_column='id_concluded', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.concluded', verbose_name='Договор')),
                ('id_supplier', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.CASCADE, to='partners.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Кредиторская задолженность',
                'verbose_name_plural': 'Кредиторская задолженность',
                'db_table': 'accounts_payable',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id_director', models.ForeignKey(blank=True, db_column='id_director', null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.director', verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Баланс предприятия',
                'verbose_name_plural': 'Баланс предприятия',
                'db_table': 'enterprise_balance',
            },
        ),
    ]
