# Generated by Django 6.0.2 on 2026-02-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False, verbose_name='ID договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Concluded',
            fields=[
                ('conclusion_dates', models.DateField(verbose_name='Дата заключения')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('id_contract', models.OneToOneField(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contracts.contract', verbose_name='Договор')),
                ('id_accountant', models.ForeignKey(db_column='id_accountant', on_delete=django.db.models.deletion.CASCADE, to='personnel.accountant', verbose_name='Бухгалтер')),
                ('id_director', models.ForeignKey(db_column='id_director', on_delete=django.db.models.deletion.CASCADE, to='personnel.director', verbose_name='Директор')),
                ('id_manager', models.ForeignKey(db_column='id_manager', on_delete=django.db.models.deletion.CASCADE, to='personnel.manager', verbose_name='Менеджер')),
                ('id_supplier', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.CASCADE, to='partners.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заключенный договор',
                'verbose_name_plural': 'Заключенные договоры',
                'db_table': 'concluded',
            },
        ),
        migrations.CreateModel(
            name='MaterialsInContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_quality_in_contract', models.FloatField(verbose_name='Качество материалов в договоре')),
                ('condition', models.CharField(max_length=200, verbose_name='Состояние/условие')),
                ('actual_quantity', models.FloatField(verbose_name='Фактическое количество')),
                ('id_contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор')),
                ('id_materials', models.ForeignKey(db_column='id_materials', on_delete=django.db.models.deletion.CASCADE, to='catalog.materials', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал в договоре',
                'verbose_name_plural': 'Материалы в договоре',
                'db_table': 'materials_in_contract',
                'unique_together': {('id_materials', 'id_contract')},
            },
        ),
    ]
