# Generated by Django 6.0.2 on 2026-03-05 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер договора"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 3, 5, 13, 19, 53, 304731, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Путь к файлу"
            ),
        ),
    ]
