# Generated by Django 6.0.2 on 2026-03-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_contract_number_contract_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="contract_number",
        ),
    ]
