# Generated by Django 6.0.2 on 2026-03-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('active', 'Активен'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
