# Generated by Django 6.0.2 on 2026-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_add_status_to_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='concluded',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поставки'),
        ),
        migrations.AddField(
            model_name='concluded',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='materialsincontract',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='concluded',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='materialsincontract',
            name='actual_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическое количество'),
        ),
        migrations.AlterField(
            model_name='materialsincontract',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состояние товара'),
        ),
        migrations.AlterField(
            model_name='materialsincontract',
            name='materials_quality_in_contract',
            field=models.FloatField(verbose_name='Количество материалов в договоре'),
        ),
    ]
