# Generated by Django 6.0.2 on 2026-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False, verbose_name='ID поставщика')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('tax_id', models.CharField(max_length=200, verbose_name='ИНН/Налоговый номер')),
                ('accounted_full_name', models.CharField(max_length=200, verbose_name='ФИО бухгалтера')),
                ('director_full_name', models.CharField(max_length=200, verbose_name='ФИО директора')),
                ('payment_details', models.CharField(max_length=500, verbose_name='Платежные реквизиты')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'supplier',
            },
        ),
    ]
