# Generated by Django 6.0.2 on 2026-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Утверждён'), ('active', 'Активен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
