# Generated by Django 6.0.2 on 2026-02-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id_warehouse', models.AutoField(primary_key=True, serialize=False, verbose_name='ID склада')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('id_materials', models.ForeignKey(db_column='id_materials', on_delete=django.db.models.deletion.CASCADE, to='catalog.materials', verbose_name='Материал')),
                ('id_warehouse', models.ForeignKey(db_column='id_warehouse', on_delete=django.db.models.deletion.CASCADE, to='warehousing.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Запас',
                'verbose_name_plural': 'Запасы',
                'db_table': 'inventory',
                'unique_together': {('id_warehouse', 'id_materials')},
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_storekeeper', models.ForeignKey(db_column='id_storekeeper', on_delete=django.db.models.deletion.CASCADE, to='personnel.storekeeper', verbose_name='Кладовщик')),
                ('id_warehouse', models.ForeignKey(db_column='id_warehouse', on_delete=django.db.models.deletion.CASCADE, to='warehousing.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Работает',
                'verbose_name_plural': 'Работают',
                'db_table': 'works',
                'unique_together': {('id_storekeeper', 'id_warehouse')},
            },
        ),
    ]
