# Generated by Django 6.0.2 on 2026-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False, verbose_name='ID администратора')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('contact_information', models.CharField(max_length=300, verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'db_table': 'admin',
            },
        ),
    ]
