# Generated by Django 6.0.2 on 2026-02-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id_materials', models.AutoField(primary_key=True, serialize=False, verbose_name='ID материала')),
                ('name', models.CharField(max_length=300, verbose_name='Название материала')),
                ('unit_of_measurement', models.CharField(max_length=30, verbose_name='Единица измерения')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id_prices', models.AutoField(primary_key=True, serialize=False, verbose_name='ID цены')),
                ('effective_dates', models.DateField(verbose_name='Дата начала действия')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('id_materials', models.ForeignKey(db_column='id_materials', on_delete=django.db.models.deletion.CASCADE, to='catalog.materials', verbose_name='Материал')),
                ('id_supplier', models.ForeignKey(db_column='id_supplier', on_delete=django.db.models.deletion.CASCADE, to='partners.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'prices',
            },
        ),
    ]
