# Generated by Django 6.0.2 on 2026-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='max_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AddField(
            model_name='materials',
            name='min_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальное количество'),
        ),
    ]
