# Generated by Django 6.0.2 on 2026-02-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActOfArrival',
            fields=[
                ('id_act_of_arrival', models.AutoField(primary_key=True, serialize=False, verbose_name='ID акта прибытия')),
                ('status', models.CharField(choices=[('Delivered', 'Доставлено'), ('Not Delivered', 'Не доставлено'), ('Cancel', 'Отменено')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Акт прибытия',
                'verbose_name_plural': 'Акты прибытия',
                'db_table': 'act_of_arrival',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False, verbose_name='ID поставки')),
                ('status', models.CharField(choices=[('Delivered', 'Доставлено'), ('Not Delivered', 'Не доставлено'), ('Cancel', 'Отменено')], max_length=20, verbose_name='Статус')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('id_act_of_arrival', models.ForeignKey(db_column='id_act_of_arrival', on_delete=django.db.models.deletion.CASCADE, to='deliveries.actofarrival', verbose_name='Акт прибытия')),
                ('id_contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_storekeeper', models.ForeignKey(db_column='id_storekeeper', on_delete=django.db.models.deletion.CASCADE, to='personnel.storekeeper', verbose_name='Кладовщик')),
                ('id_act_of_arrival', models.ForeignKey(db_column='id_act_of_arrival', on_delete=django.db.models.deletion.CASCADE, to='deliveries.actofarrival', verbose_name='Акт прибытия')),
            ],
            options={
                'verbose_name': 'Приемка поставки',
                'verbose_name_plural': 'Приемки поставок',
                'db_table': 'acceptance_of_delivery',
                'unique_together': {('id_storekeeper', 'id_act_of_arrival')},
            },
        ),
    ]
