# Generated by Django 6.0.2 on 2026-03-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actofarrival",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Ожидается"),
                    ("In Transit", "В пути"),
                    ("Delivered", "Доставлено"),
                    ("Received", "Принято"),
                    ("Not Delivered", "Не доставлено"),
                    ("Cancel", "Отменено"),
                    ("Delayed", "Задерживается"),
                ],
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Ожидается"),
                    ("In Transit", "В пути"),
                    ("Delivered", "Доставлено"),
                    ("Received", "Принято"),
                    ("Not Delivered", "Не доставлено"),
                    ("Cancel", "Отменено"),
                    ("Delayed", "Задерживается"),
                ],
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
